

name: 'dbtProject'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'bigquery_project'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  dbtProject:
    # Config indicated by + and applies to all files under models/example/
    example:
      +materialized: view

    staging: # bronze layer

      +schema: staging

    intermediate: # SILVER models folder

      +schema: intermediate                  # <-- dataset for Silver layer

    marts: # gold layer

      +schema: gold
